### ISSUE TITLE
How to static link SDL2 mixer

### ISSUE THREAD

**Issue by M4RC3L05** [nim-lang/sdl2#130]
Probrably not the best place to ask, but, how can i static link sld2_mixer?

I'm using mingw64.
Thanks.

**Comment by vanyle** [comment]
I'm reopening this because I had the same issue. Below is a command to statically link dependency to have an almost truly standalone executable. The only dlls are needed are `freetype` (because of a weird circular dependency with `harfbuzz`) and `opus`.

`
nim c --dynlibOverride:libSDL2 --dynlibOverride:libSDL2_mixer --dynlibOverride:libSDL2_image --dynlibOverride:libSDL2_ttf --dynlibOverride:libSDL2_gfx --dynlibOverride:libSDL2main --passL:"-static -lmingw32 -lSDL2main -lSDL2_image -lSDL2_mixer -lSDL2_ttf -lSDL2_gfx -lSDL2 -lfreetype.dll -lopusfile -lflac -lopus.dll -lvorbisfile -lvorbis -logg -lmpg123 -ltiff -lwebp -llzma -lpng -ljpeg -ljbig -lbz2 -lzstd -lz -ldeflate -lm -lshlwapi -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lsetupapi -lversion -luuid" source.nim
`
