### ISSUE TITLE
Remove all ocurences of cint and cuint

### ISSUE THREAD

**Issue by krux02** [nim-lang/sdl2#74]
Currently the sdl2 wrapper api exposes a lot of c types to the user, especially in the form of `cint` and `cuint`. Since I don't think sdl2 supports any 16bit architectures, where `cint` and `cuint` might be 16 bit, I would like to replace all `cint` with `int32` and all `cuint` with `uint32`. 

The idea is, that the use of the wrapper should not be required at all to deal with raw C types, when it is not absolutely necessary. If you do agree on this, I can create a pull request with all changes applied.

**Comment by Varriount** [comment]
Does Nim even run on 16-bit architectures?

**Comment by dom96** [comment]
[https://github.com/nim-lang/Nim/blob/devel/compiler/platform.nim#L189](Yes).

**Comment by krux02** [comment]
According to the SDL wiki, the supported platforms are Mac OS X, Linux, iOS, and Android. In the code, there is also support for other platforms, but none where the cint and cuint type is not 32 bit.

**Comment by yglukhov** [comment]
TBH, i can't see any practical difference between `cint/int32` and `cuint/uint32`. What is the purpose of this change? Nothing prevents the user from using `int32` and `uint32` for intaracting with SDL as it is now, no conversions needed. Since SDL has a defined C ABI it is more semantically and technically correct to keep nim interface close to that, and thus use `cint` and `cuint` if so SDL decided. Or am I missing anything?
